#!/bin/bash


# TODO: ASSERT UBUNTU 16.04
# ==========================

if [ -f /etc/os-release ]; then
  # Set $ID and $VERSION_ID in script if it exists
  . /etc/os-release
fi

case "$ID" in
  ubuntu )
    # set the architecture
    ARCH=`uname -m`

    # Normalize arch info
    if [ "${ARCH}" = "x86_64" ]; then
      ARCH="amd64"
    fi

    # Install docker
    apt-get update
    apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    # TODO: Verify the key
    # sudo apt-key fingerprint 0EBFCD88

    # TODO: SUPPORT MULTI-ARCH:
    # amd64/
    # binary-arm64
    # binary-armhf
    # binary-ppc64el
    # binary-ppc64le
    # binary-s390x

    # TODO: Move to production URL!
    add-apt-repository \
       "deb [arch=${ARCH}] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"

    apt-get update
    apt-get install -y docker-ce
    docker run -d --restart=unless-stopped 8443:443 hashbangmedia/hashbang:latest
    ;;
  * )
    echo "Unsupported OS: ${ID}"
    echo "Supported OS: Ubuntu 16.04 on amd64/x86_64"
    exit 1;
    ;;
esac
